import { LoggerService, QueryConditionInput, PageResult } from "@cs/nest-common";
import { InjectRepository } from "@cs/nest-typeorm";
import { CommonFieldsDemo } from "../common-fields-demo.entity";
import { CommonFieldsDemoRepository } from "../common-fields-demo.repository";

/**
 * 常用字段示例表（更新后） 基础服务类
 *
 * @autoGenerated 此文件由代码生成引擎自动生成，每次生成时会被覆盖。
 * 请勿直接修改此文件，自定义逻辑请写在继承子类中。
 */
export class CommonFieldsDemoServiceBase {
  constructor(protected readonly logger: LoggerService, @InjectRepository({ entity: CommonFieldsDemo, repository: CommonFieldsDemoRepository, connectionName: 'common' }) protected readonly repo: CommonFieldsDemoRepository) {
  }

  /** 分页查询 */
  public async findPage(query: QueryConditionInput): Promise<PageResult<CommonFieldsDemo>> {
    return await this.repo.findManyBase(query);
  }

  /** 根据 ID 查询单条记录 */
  public async findById(id: string): Promise<CommonFieldsDemo | null> {
    return await this.repo.findOne({ where: { id } as any });
  }

  /** 创建记录 */
  public async create(data: Partial<CommonFieldsDemo>): Promise<CommonFieldsDemo> {
    this.logger.log('创建常用字段示例表（更新后）记录', 'CommonFieldsDemoServiceBase');
    return await this.repo.saveOne(data);
  }

  /** 根据 ID 更新记录 */
  public async update(id: string, data: Partial<CommonFieldsDemo>): Promise<void> {
    await this.repo.updateByCondition(data, { id } as any);
  }

  /** 软删除记录 */
  public async remove(id: string): Promise<void> {
    await this.repo.softDeletion({ id } as any);
  }
}
