import * as path from 'path';
import { Project } from 'ts-morph';
import { GeneratorPlugin } from '../engine/plugin.interface';
import { EntityContext } from '../context/entity.context';
import { ModuleContext } from '../context/module.context';

/**
 * Module 组装插件 — 生成 NestJS 模块定义文件
 *
 * 落地规范：
 * - 使用 EntityRegistModule.forRepos() 注册实体与仓储
 * - 严格绑定 connectionName
 * - 自动收集 Service 进行 providers 注册
 */
export class ModulePlugin implements GeneratorPlugin {
  readonly name = 'ModulePlugin';
  readonly dependencies = ['TypeOrmPlugin', 'ServiceGapPlugin', 'DtoPlugin'];

  async execute(
    entityCtx: EntityContext,
    moduleCtx: ModuleContext,
    project: Project,
    outputDir: string,
  ): Promise<void> {
    // Module 只在处理模块的第一个实体时生成（避免重复）
    if (moduleCtx.entities[0] !== entityCtx) {
      return;
    }

    const filePath = path.join(outputDir, `${moduleCtx.fileName}.module.ts`);
    const sourceFile = project.createSourceFile(filePath, '', { overwrite: true });

    // ---- imports ----
    sourceFile.addImportDeclaration({
      namedImports: ['Module'],
      moduleSpecifier: '@nestjs/common',
    });
    sourceFile.addImportDeclaration({
      namedImports: ['EntityRegistModule'],
      moduleSpecifier: '@cs/nest-typeorm',
    });

    // 导入所有实体的 Entity、Repository、Service
    for (const entity of moduleCtx.entities) {
      sourceFile.addImportDeclaration({
        namedImports: [entity.className],
        moduleSpecifier: `./${entity.fileName}.entity`,
      });
      sourceFile.addImportDeclaration({
        namedImports: [`${entity.className}Repository`],
        moduleSpecifier: `./${entity.fileName}.repository`,
      });

      if (entity.generateService) {
        sourceFile.addImportDeclaration({
          namedImports: [`${entity.className}Service`],
          moduleSpecifier: `./${entity.fileName}.service`,
        });
      }
    }

    // ---- 构建 EntityRegistModule.forRepos 参数 ----
    const repoEntries = moduleCtx.entities.map((entity) => {
      const parts = [
        `entity: ${entity.className}`,
        `repository: ${entity.className}Repository`,
      ];
      if (entity.hasCustomConnection) {
        parts.push(`connectionName: '${entity.connectionName}'`);
      }
      return `{ ${parts.join(', ')} }`;
    });

    const importsArray = `[
      EntityRegistModule.forRepos([
        ${repoEntries.join(',\n        ')}
      ])
    ]`;

    // ---- 收集 providers 和 controllers ----
    const providers = moduleCtx.entities
      .filter((e) => e.generateService)
      .map((e) => `${e.className}Service`);

    const controllers: string[] = [];
    // 预留 Controller 注册位（ControllerPlugin 扩展时自动填充）

    // ---- Module Class ----
    const moduleArgs = [
      `imports: ${importsArray}`,
      controllers.length > 0 ? `controllers: [${controllers.join(', ')}]` : `controllers: []`,
      `providers: [${providers.join(', ')}]`,
      `exports: [${providers.join(', ')}]`,
    ];

    sourceFile.addClass({
      name: `${moduleCtx.className}Module`,
      isExported: true,
      decorators: [
        {
          name: 'Module',
          arguments: [`{\n  ${moduleArgs.join(',\n  ')}\n}`],
        },
      ],
      docs: [
        {
          description: `${moduleCtx.displayName}\n@autoGenerated 此文件由代码生成引擎自动生成`,
        },
      ],
    });

    console.log(`    ✓ Module: ${moduleCtx.className}Module → ${moduleCtx.fileName}.module.ts`);
  }
}
