import * as path from 'path';
import * as fs from 'fs';
import { Project, Scope } from 'ts-morph';
import { GeneratorPlugin } from '../engine/plugin.interface';
import { EntityContext } from '../context/entity.context';
import { ModuleContext } from '../context/module.context';

/**
 * 代沟服务插件 (Generation Gap Pattern)
 *
 * 生成策略：
 * - base/xxx.service.base.ts  → 每次强覆盖（标准 CRUD + 平台规范注入）
 * - xxx.service.ts            → 仅首次生成（开发者 / AI Agent 扩展区）
 *
 * 这样做的好处：
 * 1. JSON 配置变更后重新生成不会丢失自定义逻辑
 * 2. AI Agent 可以安全地在扩展子类中注入 Skills
 * 3. 基础 CRUD 始终与最新配置保持同步
 */
export class ServiceGapPlugin implements GeneratorPlugin {
  readonly name = 'ServiceGapPlugin';
  readonly dependencies = ['TypeOrmPlugin'];

  async execute(
    entityCtx: EntityContext,
    _moduleCtx: ModuleContext,
    project: Project,
    outputDir: string,
  ): Promise<void> {
    if (!entityCtx.generateService) {
      console.log(`    ⏭️ 跳过 Service 生成（generateService=false）`);
      return;
    }

    this.generateBaseService(entityCtx, project, outputDir);
    this.generateCustomService(entityCtx, project, outputDir);
  }

  // =========================================================================
  // Base Service（每次强覆盖）
  // =========================================================================

  private generateBaseService(ctx: EntityContext, project: Project, outputDir: string): void {
    // 确保 base 目录存在
    const baseDir = path.join(outputDir, 'base');
    if (!fs.existsSync(baseDir)) {
      fs.mkdirSync(baseDir, { recursive: true });
    }

    const filePath = path.join(baseDir, `${ctx.fileName}.service.base.ts`);
    const sourceFile = project.createSourceFile(filePath, '', { overwrite: true });

    // ---- imports ----
    sourceFile.addImportDeclaration({
      namedImports: ['LoggerService', 'QueryConditionInput', 'PageResult'],
      moduleSpecifier: '@cs/nest-common',
    });
    sourceFile.addImportDeclaration({
      namedImports: ['InjectRepository'],
      moduleSpecifier: '@cs/nest-typeorm',
    });
    sourceFile.addImportDeclaration({
      namedImports: [ctx.className],
      moduleSpecifier: `../${ctx.fileName}.entity`,
    });
    sourceFile.addImportDeclaration({
      namedImports: [`${ctx.className}Repository`],
      moduleSpecifier: `../${ctx.fileName}.repository`,
    });

    // ---- Base Service Class ----
    const baseClass = sourceFile.addClass({
      name: `${ctx.className}ServiceBase`,
      isExported: true,
      docs: [
        {
          description: [
            `${ctx.raw.entityName} 基础服务类`,
            '',
            '@autoGenerated 此文件由代码生成引擎自动生成，每次生成时会被覆盖。',
            '请勿直接修改此文件，自定义逻辑请写在继承子类中。',
          ].join('\n'),
        },
      ],
    });

    // ---- 构造函数：注入 Logger + Repository ----
    const injectArgs = ctx.hasCustomConnection
      ? `{ entity: ${ctx.className}, repository: ${ctx.className}Repository, connectionName: '${ctx.connectionName}' }`
      : `{ entity: ${ctx.className}, repository: ${ctx.className}Repository }`;

    baseClass.addConstructor({
      parameters: [
        {
          name: 'logger',
          type: 'LoggerService',
          scope: Scope.Protected,
          isReadonly: true,
        },
        {
          name: 'repo',
          type: `${ctx.className}Repository`,
          scope: Scope.Protected,
          isReadonly: true,
          decorators: [
            {
              name: 'InjectRepository',
              arguments: [injectArgs],
            },
          ],
        },
      ],
    });

    // ---- 标准 CRUD 方法 ----

    // findPage — 分页查询
    baseClass.addMethod({
      name: 'findPage',
      isAsync: true,
      scope: Scope.Public,
      parameters: [{ name: 'query', type: 'QueryConditionInput' }],
      returnType: `Promise<PageResult<${ctx.className}>>`,
      docs: [{ description: '分页查询' }],
      statements: `return await this.repo.findManyBase(query);`,
    });

    // findById — 根据 ID 查询
    baseClass.addMethod({
      name: 'findById',
      isAsync: true,
      scope: Scope.Public,
      parameters: [{ name: 'id', type: 'string' }],
      returnType: `Promise<${ctx.className} | null>`,
      docs: [{ description: '根据 ID 查询单条记录' }],
      statements: `return await this.repo.findOne({ where: { id } as any });`,
    });

    // create — 创建
    baseClass.addMethod({
      name: 'create',
      isAsync: true,
      scope: Scope.Public,
      parameters: [{ name: 'data', type: `Partial<${ctx.className}>` }],
      returnType: `Promise<${ctx.className}>`,
      docs: [{ description: '创建记录' }],
      statements: [
        `this.logger.log('创建${ctx.raw.entityName}记录', '${ctx.className}ServiceBase');`,
        `return await this.repo.saveOne(data);`,
      ].join('\n'),
    });

    // update — 更新
    baseClass.addMethod({
      name: 'update',
      isAsync: true,
      scope: Scope.Public,
      parameters: [
        { name: 'id', type: 'string' },
        { name: 'data', type: `Partial<${ctx.className}>` },
      ],
      returnType: `Promise<void>`,
      docs: [{ description: '根据 ID 更新记录' }],
      statements: `await this.repo.updateByCondition(data, { id } as any);`,
    });

    // remove — 软删除
    baseClass.addMethod({
      name: 'remove',
      isAsync: true,
      scope: Scope.Public,
      parameters: [{ name: 'id', type: 'string' }],
      returnType: `Promise<void>`,
      docs: [{ description: '软删除记录' }],
      statements: `await this.repo.softDeletion({ id } as any);`,
    });

    console.log(`    ✓ BaseService: ${ctx.className}ServiceBase → base/${ctx.fileName}.service.base.ts`);
  }

  // =========================================================================
  // Custom Service（仅首次生成，保护手写代码）
  // =========================================================================

  private generateCustomService(ctx: EntityContext, project: Project, outputDir: string): void {
    const filePath = path.join(outputDir, `${ctx.fileName}.service.ts`);

    // 🛡️ 核心防御：文件已存在则跳过，保护自定义代码
    if (fs.existsSync(filePath)) {
      console.log(`    🛡️ 跳过: ${ctx.fileName}.service.ts 已存在（保护自定义代码）`);
      return;
    }

    const sourceFile = project.createSourceFile(filePath, '');

    sourceFile.addImportDeclaration({
      namedImports: ['Injectable'],
      moduleSpecifier: '@nestjs/common',
    });
    sourceFile.addImportDeclaration({
      namedImports: [`${ctx.className}ServiceBase`],
      moduleSpecifier: `./base/${ctx.fileName}.service.base`,
    });

    sourceFile.addClass({
      name: `${ctx.className}Service`,
      extends: `${ctx.className}ServiceBase`,
      isExported: true,
      decorators: [
        {
          name: 'Injectable',
          arguments: [],
        },
      ],
      docs: [
        {
          description: [
            `${ctx.raw.entityName} 业务扩展服务`,
            '',
            'AI Agent 或开发者可在此处编写自定义业务逻辑。',
            '低代码引擎的再次生成不会覆盖此文件。',
          ].join('\n'),
        },
      ],
    });

    console.log(`    ✓ Service: ${ctx.className}Service → ${ctx.fileName}.service.ts`);
  }
}
