import * as path from 'path';
import { Project } from 'ts-morph';
import { GeneratorPlugin } from '../engine/plugin.interface';
import { EntityContext } from '../context/entity.context';
import { ModuleContext } from '../context/module.context';
import { mapFieldTypeToTs, mapFieldTypeToDb } from '../utils/naming';

/**
 * TypeORM 插件 — 生成 Entity 和 Repository 文件
 *
 * 落地规范：
 * - Entity 继承指定的 @cs/nest-typeorm 基类
 * - Repository 独立文件，继承 BaseRepository<T>
 * - 审计字段由 EntityContext 预过滤，不会重复生成
 */
export class TypeOrmPlugin implements GeneratorPlugin {
  readonly name = 'TypeOrmPlugin';

  async execute(
    entityCtx: EntityContext,
    _moduleCtx: ModuleContext,
    project: Project,
    outputDir: string,
  ): Promise<void> {
    this.generateEntity(entityCtx, project, outputDir);
    this.generateRepository(entityCtx, project, outputDir);
  }

  // =========================================================================
  // Entity 生成
  // =========================================================================

  private generateEntity(ctx: EntityContext, project: Project, outputDir: string): void {
    const filePath = path.join(outputDir, `${ctx.fileName}.entity.ts`);
    const sourceFile = project.createSourceFile(filePath, '', { overwrite: true });

    // ---- imports ----
    const typeormImports: string[] = ['Entity'];

    // 是否有需要 PrimaryColumn 的字段（裸实体的主键）
    const needsPrimaryColumn = ctx.primaryKeys.some(
      (pk) => ctx.businessFields.includes(pk),
    );
    if (needsPrimaryColumn) {
      typeormImports.push('PrimaryColumn');
    }
    if (ctx.businessFields.length > 0) {
      typeormImports.push('Column');
    }

    sourceFile.addImportDeclaration({
      namedImports: typeormImports,
      moduleSpecifier: 'typeorm',
    });
    sourceFile.addImportDeclaration({
      namedImports: [ctx.baseEntityClass, 'registerEntity'],
      moduleSpecifier: '@cs/nest-typeorm',
    });

    // ---- Entity Class ----
    const entityClass = sourceFile.addClass({
      name: ctx.className,
      extends: ctx.baseEntityClass,
      isExported: true,
      decorators: [
        {
          name: 'Entity',
          arguments: [`'${ctx.raw.tableName}'`],
        },
      ],
      docs: [
        {
          description: `${ctx.raw.entityName}\n@autoGenerated 此文件由代码生成引擎自动生成`,
        },
      ],
    });

    // ---- 业务字段 ----
    for (const field of ctx.businessFields) {
      const isPk = field.raw.primaryKey;
      const tsType = mapFieldTypeToTs(field.raw.fieldType);
      const dbType = mapFieldTypeToDb(field.raw.fieldType);
      const isRequired = field.raw.required && !field.raw.nullable;

      // 构建列选项
      const columnOpts: Record<string, any> = {
        name: field.dbColumnName,
        type: dbType,
        comment: field.raw.fieldName,
      };
      if (field.raw.length) columnOpts.length = field.raw.length;
      if (field.raw.precision) columnOpts.precision = field.raw.precision;
      if (field.raw.scale !== undefined) columnOpts.scale = field.raw.scale;
      if (field.raw.nullable || !field.raw.required) columnOpts.nullable = true;
      if (field.raw.defaultValue !== undefined) columnOpts.default = field.raw.defaultValue;

      const decoratorName = isPk ? 'PrimaryColumn' : 'Column';
      const decoratorArgs = this.formatColumnOptions(columnOpts);

      entityClass.addProperty({
        name: field.propertyName,
        type: tsType,
        hasExclamationToken: isRequired,
        hasQuestionToken: !isRequired,
        decorators: [
          {
            name: decoratorName,
            arguments: [decoratorArgs],
          },
        ],
      });
    }

    // ---- registerEntity() 注册调用（@cs/nest-typeorm 规范要求） ----
    const registerOpts: string[] = [`entity: ${ctx.className}`];
    if (ctx.hasCustomConnection) {
      registerOpts.push(`connectionName: '${ctx.connectionName}'`);
    }
    sourceFile.addStatements(
      `\nregisterEntity({ ${registerOpts.join(', ')} });`,
    );

    console.log(`    ✓ Entity: ${ctx.className} → ${ctx.fileName}.entity.ts`);
  }

  // =========================================================================
  // Repository 生成
  // =========================================================================

  private generateRepository(ctx: EntityContext, project: Project, outputDir: string): void {
    const filePath = path.join(outputDir, `${ctx.fileName}.repository.ts`);
    const sourceFile = project.createSourceFile(filePath, '', { overwrite: true });

    sourceFile.addImportDeclaration({
      namedImports: ['Injectable'],
      moduleSpecifier: '@nestjs/common',
    });
    sourceFile.addImportDeclaration({
      namedImports: ['BaseRepository'],
      moduleSpecifier: '@cs/nest-typeorm',
    });
    sourceFile.addImportDeclaration({
      namedImports: [ctx.className],
      moduleSpecifier: `./${ctx.fileName}.entity`,
    });

    sourceFile.addClass({
      name: `${ctx.className}Repository`,
      extends: `BaseRepository<${ctx.className}>`,
      isExported: true,
      decorators: [
        {
          name: 'Injectable',
          arguments: [],
        },
      ],
      docs: [
        {
          description: `${ctx.raw.entityName} 仓储\n@autoGenerated 此文件由代码生成引擎自动生成`,
        },
      ],
    });

    console.log(`    ✓ Repository: ${ctx.className}Repository → ${ctx.fileName}.repository.ts`);
  }

  // =========================================================================
  // 工具方法
  // =========================================================================

  /**
   * 将列选项对象格式化为 ts-morph 可用的参数字符串
   */
  private formatColumnOptions(opts: Record<string, any>): string {
    const entries = Object.entries(opts).map(([key, value]) => {
      return `${key}: ${JSON.stringify(value)}`;
    });
    return `{ ${entries.join(', ')} }`;
  }
}
