import { Entity, Column } from "typeorm";
import { HasPrimaryFullEntity, registerEntity } from "@cs/nest-typeorm";

/**
 * 常用字段示例表（更新后）
 * @autoGenerated 此文件由代码生成引擎自动生成
 */
@Entity('common_fields_demo')
export class CommonFieldsDemo extends HasPrimaryFullEntity {
  @Column({ name: "code", type: "varchar", comment: "编码", length: 50 })
  code!: string;
  @Column({ name: "name", type: "varchar", comment: "名称", length: 100 })
  name!: string;
}

registerEntity({ entity: CommonFieldsDemo, connectionName: 'common' });
