import { Module } from "@nestjs/common";
import { EntityRegistModule } from "@cs/nest-typeorm";
import { CommonFieldsDemo } from "./common-fields-demo.entity";
import { CommonFieldsDemoRepository } from "./common-fields-demo.repository";
import { CommonFieldsDemoService } from "./common-fields-demo.service";

/**
 * 常用字段模块
 * @autoGenerated 此文件由代码生成引擎自动生成
 */
@Module({
  imports: [
    EntityRegistModule.forRepos([
      { entity: CommonFieldsDemo, repository: CommonFieldsDemoRepository, connectionName: 'common' }
    ])
  ],
  controllers: [],
  providers: [CommonFieldsDemoService],
  exports: [CommonFieldsDemoService]
})
export class CommonFieldsModule {
}
