import { Injectable } from "@nestjs/common";
import { BaseRepository } from "@cs/nest-typeorm";
import { CommonFieldsDemo } from "./common-fields-demo.entity";

/**
 * 常用字段示例表（更新后） 仓储
 * @autoGenerated 此文件由代码生成引擎自动生成
 */
@Injectable()
export class CommonFieldsDemoRepository extends BaseRepository<CommonFieldsDemo> {
}
